- name: Get running processes
  become: yes
  shell: "ps -ef | grep -v grep | grep -w {{ APP_NAME }} | awk '{print $2}'"
  register: running_processes

- name: Kill running processes
  become: yes
  shell: "kill {{ item }}"
  with_items: "{{ running_processes.stdout_lines }}"

- wait_for:
    path: "/proc/{{ item }}/status"
    state: absent
  with_items: "{{ running_processes.stdout_lines }}"
  ignore_errors: yes
  become: yes
  register: killed_processes

- name: Force kill stuck processes
  become: yes
  shell: "kill -9 {{ item }}"
  with_items: "{{ killed_processes.results | select('failed') | map(attribute='item') | list }}"

- name: Creates petclinic directory
  file:
    path: "{{ item }}"
    state: directory
    owner: devops
    group: devops
    mode: u=rwx,g=r,o=r
  with_items:
    - "{{ DEPLOY_PATH }}"
    - "{{ LOG_PATH }}"

- name: Copy petclinic JAR to tomcat
  become: yes
  copy:
    src: "{{ BUILD_PATH }}/target/spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar"
    dest: "{{ DEPLOY_PATH }}/{{ APP_NAME }}.jar"
    owner: devops
    group: devops
    mode: u=rw,g=r,o=r

- name: read file from server
  shell: cat /etc/petclinic/petclinic.conf
  register: data
  when: IS_STACKTRACE_ENABLE == 'true'

- name: Trigger shell commands
  command: "{{ item }}"
  become: yes
  with_items:
    - jar xf /home/devops/petclinic/petclinic.jar BOOT-INF/classes/application.properties
    - sed -i "s/tag_Name=petclinic/tag_Name={{ data.stdout }}/g" BOOT-INF/classes/application.properties
    - jar uf /home/devops/petclinic/petclinic.jar BOOT-INF/classes/application.properties
  when: IS_STACKTRACE_ENABLE == 'true'

- name: Download apm jar file
  get_url:
    url: https://search.maven.org/remotecontent?filepath=co/elastic/apm/elastic-apm-agent/1.6.1/elastic-apm-agent-1.6.1.jar
    dest: /home/devops/petclinic/apm.jar
    mode: '0777'

- name: Copy petclinic service script to /etc/init.d/ dir
  become: yes
  template:
    src: petclinic
    dest: "/etc/init.d/petclinic"
    force: yes
    mode: u=rwx,g=rx,o=rx
  when: IS_STACKTRACE_ENABLE == 'false'

- name: Copy petclinic service script to /etc/init.d/ dir
  become: yes
  template:
    src: petclinic-stacktrace
    dest: "/etc/init.d/petclinic"
    force: yes
    mode: u=rwx,g=rx,o=rx
  when: IS_STACKTRACE_ENABLE == 'true'

- name: Start and enable petclinic services for automatic start
  become: yes
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: petclinic
  when: IS_PRIMARY_DEPLOYMENT == 'true'
